package resetgen

import (
	"bytes"
	"fmt"
	"go/ast"
)

// Generate builds the contents of a reset.gen.go file for the given package.
func Generate(pkg string, structs []StructInfo) []byte {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by resetgen. DO NOT EDIT.\n")
	buf.WriteString("package " + pkg + "\n\n")

	for _, s := range structs {
		writeResetMethod(&buf, s)
	}

	return buf.Bytes()
}

// writeResetMethod writes a Reset method for a single struct
func writeResetMethod(buf *bytes.Buffer, s StructInfo) {
	buf.WriteString(fmt.Sprintf("// Reset resets fields of %s to zero values\n", s.Name))
	buf.WriteString(fmt.Sprintf("func (r *%s) Reset() {\n", s.Name))
	buf.WriteString("\tif r == nil {\n\t\treturn\n\t}\n\n")

	for _, f := range s.Fields {
		field := "r." + f.Name

		switch t := f.Type.(type) {

		// primitive values
		case *ast.Ident:
			switch t.Name {
			case "int", "int8", "int16", "int32", "int64",
				"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
				"float32", "float64",
				"complex64", "complex128":
				buf.WriteString("\t" + field + " = 0\n")

			case "string":
				buf.WriteString("\t" + field + ` = ""` + "\n")

			case "bool":
				buf.WriteString("\t" + field + " = false\n")

			default:
				buf.WriteString(indent(callReset(field)))
			}

		// slices
		case *ast.ArrayType:
			if t.Len == nil {
				buf.WriteString("\t" + field + " = " + field + "[:0]\n")
			}

		// maps
		case *ast.MapType:
			buf.WriteString("\tclear(" + field + ")\n")

		// pointers
		case *ast.StarExpr:

			buf.WriteString(fmt.Sprintf("\tif %s != nil {\n", field))

			switch inner := t.X.(type) {

			case *ast.Ident:
				switch inner.Name {

				// pointer to primitive
				case "int", "int8", "int16", "int32", "int64",
					"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
					"float32", "float64",
					"complex64", "complex128":
					buf.WriteString("\t\t*" + field + " = 0\n")

				case "string":
					buf.WriteString("\t\t*" + field + ` = ""` + "\n")

				case "bool":
					buf.WriteString("\t\t*" + field + " = false\n")

				default:
					// pointer to struct
					buf.WriteString(indent(callReset(field)))
				}

			default:
				buf.WriteString(indent(callReset(field)))
			}

			buf.WriteString("\t}\n")

		default:
			buf.WriteString(indent(callReset(field)))
		}
	}

	buf.WriteString("}\n\n")
}

// callReset returns code that calls Reset on a value if it implements
// an interface with a Reset method
func callReset(expr string) string {
	return fmt.Sprintf(
		`if resetter, ok := interface{}(%s).(interface{ Reset() }); ok {
			resetter.Reset()
		}`,
		expr,
	)
}

// indent adds one tab to each non-empty line of a generated code fragment
func indent(s string) string {
	var buf bytes.Buffer
	startOfLine := true

	for i := 0; i < len(s); i++ {
		if startOfLine && s[i] != '\n' {
			buf.WriteByte('\t')
			startOfLine = false
		}

		buf.WriteByte(s[i])

		if s[i] == '\n' {
			startOfLine = true
		}
	}

	return buf.String()
}
