// Code generated by resetgen. DO NOT EDIT.
package testdata

// Reset resets fields of ResetableStruct to zero values
func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}

	r.i = 0
	r.str = ""
	if r.strP != nil {
		*r.strP = ""
	}
	r.s = r.s[:0]
	clear(r.m)
	if r.child != nil {
		if resetter, ok := interface{}(r.child).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
}
